server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-05-08T20:54:58.140+08:00[Asia/Shanghai]
#            - Before=2020-06-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai],2020-06-08T11:59:36.102+08:00[Asia/Shanghai]
#            - Cookie=uname,zyy
#            - Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由
#  curl http://localhost:9527/payment/lb --cookie "uname=zyy" -H "X-Request-Id:11"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


